export let classOne = [
  {
    id: 1,
    name: "sabbir",
    imgUrl:
      "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
    scores: "A+",
    percentage: 98,
  },
  {
    id: 2,
    name: "Fardin",
    imgUrl: "https://i.pravatar.cc/250?u=mail@ashallendesign.co.uk",
    scores: "A",
    percentage: 79,
  },
  {
    id: 3,
    name: "Shamim",
    imgUrl: "https://eu.ui-avatars.com/api/?name=John+Doe&size=250",
    scores: "B+",
    percentage: 65,
  },
  {
    id: 4,
    name: "mahir",
    imgUrl: "https://avatar.iran.liara.run/public/boy?username=Ash",
    scores: "A+",
    percentage: 95,
  },
  {
    id: 5,
    name: "jahid",
    imgUrl:
      "https://api.dicebear.com/7.x/adventurer-neutral/svg?seed=mail@ashallendesign.co.uk",
    scores: "C",
    percentage: 45,
  },
  {
    id: 6,
    name: "Shourav",
    imgUrl: "https://robohash.org/mail@ashallendesign.co.uk",
    scores: "A-",
    percentage: 75,
  },
  {
    id: 7,
    name: "Ashik",
    imgUrl: "https://dummyimage.com/300.png/09f/fff&text=Ash+Allen",

    scores: "B",
    percentage: 56,
  },
  {
    id: 8,
    name: "Rohan",
    imgUrl: "https://baconmockup.com/250/250/",
    scores: "D",
    percentage: 35,
  },
  {
    id: 9,
    name: "Mashaekh",
    imgUrl: "https://placekitten.com/250/250",
    scores: "F",
    percentage: 32,
  },
  {
    id: 10,
    name: "Rakibul",
    imgUrl: "https://placebear.com/250/250",
    scores: "A+",
    percentage: 96,
  },
  {
    id: 11,
    name: "Faiaz",
    imgUrl: "https://loremflickr.com/250/250/dog",
    scores: "B+",
    percentage: 67,
  },
  {
    id: 12,
    name: "Mahmud",
    imgUrl: "https://placebeard.it/250/250",
    scores: "C+",
    percentage: 49,
  },
];

export let classaTow = [
  {
    id: 1,
    name: "Avishek",
    imgUrl: "https://dummyimage.com/300.png/09f/fff&text=Ash+Allen",
    scores: "B",
    percentage: 56,
  },
  {
    id: 2,
    name: "Saad",
    imgUrl: "https://robohash.org/mail@ashallendesign.co.uk",
    scores: "A-",
    percentage: 75,
  },
  {
    id: 3,
    name: "Masud",
    imgUrl: "https://placekitten.com/250/250",
    scores: "F",
    percentage: 32,
  },
  {
    id: 4,
    name: "Tahsin",
    imgUrl: "https://placebear.com/250/250",
    scores: "A+",
    percentage: 96,
  },
  {
    id: 5,
    name: "Imon",
    imgUrl: "https://placebeard.it/250/250",
    scores: "C+",
    percentage: 49,
  },
  {
    id: 6,
    name: "arman",
    imgUrl: "https://i.pravatar.cc/250?u=mail@ashallendesign.co.uk",
    scores: "A",
    percentage: 79,
  },
  {
    id: 7,
    name: "Sohel",
    imgUrl:
      "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
    scores: "A+",
    percentage: 98,
  },
  {
    id: 8,
    name: "Ra Him",
    imgUrl: "https://baconmockup.com/250/250/",
    scores: "D",
    percentage: 35,
  },
  {
    id: 9,
    name: "Mishkat",
    imgUrl: "https://eu.ui-avatars.com/api/?name=John+Doe&size=250",
    scores: "B+",
    percentage: 65,
  },
  {
    id: 10,
    name: "Asadullah",
    imgUrl: "https://avatar.iran.liara.run/public/boy?username=Ash",
    scores: "A+",
    percentage: 95,
  },
  {
    id: 11,
    name: "Tajrian",
    imgUrl: "https://loremflickr.com/250/250/dog",
    scores: "B+",
    percentage: 67,
  },
  {
    id: 12,
    name: "Sadik",
    imgUrl:
      "https://api.dicebear.com/7.x/adventurer-neutral/svg?seed=mail@ashallendesign.co.uk",
    scores: "C",
    percentage: 45,
  },
];

export let classThree = [
  {
    id: 1,
    name: "Minhaj",
    imgUrl: "https://loremflickr.com/250/250/dog",
    scores: "B+",
    percentage: 67,
  },
  {
    id: 2,
    name: "moula",
    imgUrl: "https://placekitten.com/250/250",
    scores: "F",
    percentage: 32,
  },
  {
    id: 3,
    name: "Taufiq",
    imgUrl: "https://eu.ui-avatars.com/api/?name=John+Doe&size=250",
    scores: "B+",
    percentage: 65,
  },
  {
    id: 4,
    name: "Tinun",
    imgUrl: "https://baconmockup.com/250/250/",
    scores: "D",
    percentage: 35,
  },
  {
    id: 5,
    name: "Riad",
    imgUrl:
      "https://api.dicebear.com/7.x/adventurer-neutral/svg?seed=mail@ashallendesign.co.uk",
    scores: "C",
    percentage: 45,
  },
  {
    id: 6,
    name: "debesh",
    imgUrl: "https://placebeard.it/250/250",
    scores: "C+",
    percentage: 49,
  },
  {
    id: 7,
    name: "Khijir",
    imgUrl: "https://dummyimage.com/300.png/09f/fff&text=Ash+Allen",
    scores: "B",
    percentage: 56,
  },
  {
    id: 8,
    name: "mehrab",
    imgUrl: "https://avatar.iran.liara.run/public/boy?username=Ash",
    scores: "A+",
    percentage: 95,
  },
  {
    id: 9,
    name: "Simanto",
    imgUrl: "https://i.pravatar.cc/250?u=mail@ashallendesign.co.uk",
    scores: "A",
    percentage: 79,
  },
  {
    id: 10,
    name: "Ahnaf Ibrahim",
    imgUrl: "https://placebear.com/250/250",
    scores: "A+",
    percentage: 96,
  },
  {
    id: 11,
    name: "Mahadi",
    imgUrl:
      "https://www.gravatar.com/avatar/2c7d99fe281ecd3bcd65ab915bac6dd5?s=250",
    scores: "A+",
    percentage: 98,
  },
  {
    id: 12,
    name: "Joy",
    imgUrl: "https://robohash.org/mail@ashallendesign.co.uk",
    scores: "A-",
    percentage: 75,
  },
];
